--PROBLEM 1--

SELECT
  d.DEPTNO,
  d.DEPTNAME,
  COUNT(e.EMPNO) AS "No. EMP",
  ROUND(AVG(e.SALARY), 2) AS "DEPT-AVG-INCOME"
FROM DEPARTMENT AS d
JOIN EMPLOYEE AS e
  ON d.DEPTNO = e.WORKDEPT
GROUP BY
  d.DEPTNO,
  d.DEPTNAME
HAVING
  COUNT(e.EMPNO) >= 4
ORDER BY
  "DEPT-AVG-INCOME" DESC;
